[package]
name = "blitzar-sys"
version = "0.0.0" 
edition = "2021"
repository = "https://github.com/spaceandtimelabs/blitzar"

exclude = ["/target", "/Cargo.lock"]
include = ["/src", "build.rs", "Cargo.toml", "*.so*"]

[dependencies]
